/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Or Update Application
         * @description Insert or update a CRM application row.
         */
        post: operations["create_or_update_application_api_applications_post"];
        /**
         * Delete Application
         * @description Delete an application's files and CRM rows, then record a dismissal.
         */
        delete: operations["delete_application_api_applications_delete"];
        options?: never;
        head?: never;
        /**
         * Patch Application
         * @description Update only the matched CRM row (notes and/or status).
         */
        patch: operations["patch_application_api_applications_patch"];
        trace?: never;
    };
    "/api/applications/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Application
         * @description Update only the matched CRM row (notes and/or status).
         */
        patch: operations["patch_application_api_applications_notes_patch"];
        trace?: never;
    };
    "/api/applied-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applied Urls
         * @description Return every job URL already present in the CRM tracker.
         */
        get: operations["applied_urls_api_applied_urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approved-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Approved Index
         * @description Lightweight index of approved jobs for client-side lookups.
         */
        get: operations["approved_index_api_approved_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crm-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tracker
         * @description Return CRM tracker rows, newest application first, with contact emails.
         */
        get: operations["get_tracker_api_crm_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description Return the queryable SQLite-backed dataset view names.
         */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dismissed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dismissed
         * @description Return every job the user has dismissed.
         */
        get: operations["list_dismissed_api_dismissed_get"];
        put?: never;
        /**
         * Dismiss Job
         * @description Permanently record a dismissal in SQLite and the JSON sync file.
         */
        post: operations["dismiss_job_api_dismissed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description Return the queryable SQLite-backed dataset view names.
         */
        get: operations["list_datasets_api_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Application
         * @description Generate a tailored ATS application, or report an existing task.
         */
        post: operations["generate_application_api_generate_application_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-application/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generation Status
         * @description Poll the status of a background application-generation task.
         */
        get: operations["generation_status_api_generate_application_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Email
         * @description Draft an application email for a job.
         */
        post: operations["generate_email_api_generate_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-descriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Descriptions
         * @description Resolve job descriptions by URL, falling back to (company, position).
         */
        get: operations["job_descriptions_api_job_descriptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Return job records for a named SQLite view.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull And Sync
         * @description Pull ``origin/main`` and ingest new jobs into SQLite.
         */
        get: operations["pull_and_sync_api_pull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run-scraper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Scraper
         * @description Spawn the local scraper subprocess (rejecting a concurrent run).
         */
        post: operations["run_scraper_api_run_scraper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scraper-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scraper Logs
         * @description Return the tail of the local scraper log, if present.
         */
        get: operations["scraper_logs_api_scraper_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scraper-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scraper Status
         * @description Report whether the local scraper subprocess is still running.
         */
        get: operations["scraper_status_api_scraper_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stop-scraper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Scraper
         * @description Terminate the running scraper subprocess, if any.
         */
        post: operations["stop_scraper_api_stop_scraper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull And Sync
         * @description Pull ``origin/main`` and ingest new jobs into SQLite.
         */
        get: operations["pull_and_sync_api_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tracker
         * @description Return CRM tracker rows, newest application first, with contact emails.
         */
        get: operations["get_tracker_api_tracker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracker/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Tracker
         * @description Clear the in-memory tracker/job caches.
         */
        get: operations["refresh_tracker_api_tracker_refresh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trigger-github-scraper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Scraper
         * @description Spawn the local scraper subprocess (rejecting a concurrent run).
         */
        post: operations["run_scraper_api_trigger_github_scraper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationDeleteRequest
         * @description Optional body for ``DELETE /api/applications``.
         */
        ApplicationDeleteRequest: {
            /** Company */
            company?: string | null;
            /** Cv Pdf Path */
            cv_pdf_path?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Position */
            position?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ApplicationPatchRequest
         * @description Body for ``PATCH /api/applications`` and ``/api/applications/notes``.
         */
        ApplicationPatchRequest: {
            /** Company */
            company?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Position */
            position?: string | null;
            /** Status */
            status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ApplicationUpsertRequest
         * @description Body for ``POST /api/applications``.
         */
        ApplicationUpsertRequest: {
            /**
             * Company
             * @default
             */
            company: string;
            /** Cover Pdf Path */
            cover_pdf_path?: string | null;
            /** Cv Pdf Path */
            cv_pdf_path?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /** Notes */
            notes?: string | null;
            /**
             * Position
             * @default
             */
            position: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ApprovedIndexEntry
         * @description A row of ``GET /api/approved-index``.
         */
        ApprovedIndexEntry: {
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * DismissRequest
         * @description Body for ``POST /api/dismissed``.
         */
        DismissRequest: {
            /** Company */
            company?: string | null;
            /** Job Url */
            job_url?: string | null;
            /** Position */
            position?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * GenerateApplicationRequest
         * @description Body for ``POST /api/generate-application``.
         */
        GenerateApplicationRequest: {
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /** Language */
            language?: string | null;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Position
             * @default
             */
            position: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * GenerateEmailRequest
         * @description Body for ``POST /api/generate-email``.
         */
        GenerateEmailRequest: {
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /**
             * Position
             * @default
             */
            position: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobRecord
         * @description A row of ``GET /api/jobs`` (one dataset view record).
         *
         *     Extra columns are preserved so future SQL fields do not break the response
         *     model; the declared fields mirror the current query projection.
         */
        JobRecord: {
            /** Ai Reason */
            ai_reason?: string | null;
            /** Ai Score */
            ai_score?: string | null;
            /**
             * Company
             * @default
             */
            company: string;
            /** Date Posted */
            date_posted?: string | null;
            /** Description */
            description?: string | null;
            /** Evaluated At */
            evaluated_at?: string | null;
            /** First Seen */
            first_seen?: string | null;
            /** Gemini Gaps */
            gemini_gaps?: string | null;
            /** Gemini Interview Chance */
            gemini_interview_chance?: string | null;
            /** Gemini Matched Skills */
            gemini_matched_skills?: string | null;
            /**
             * Gemini Score
             * @default 0
             */
            gemini_score: number;
            /** Gemini Status */
            gemini_status?: string | null;
            /** Gemini Summary */
            gemini_summary?: string | null;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /** Location */
            location?: string | null;
            /** Matched Skills */
            matched_skills?: string | null;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Scraped At */
            scraped_at?: string | null;
            /** Target Archetype */
            target_archetype?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * MessageResponse
         * @description Generic ``{"success": ..., "message": ...}`` acknowledgement.
         */
        MessageResponse: {
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /**
         * ScraperRunRequest
         * @description Body for ``POST /api/run-scraper`` and its alias.
         */
        ScraperRunRequest: {
            /**
             * Days
             * @default 1
             */
            days: number | string;
            /**
             * Portal
             * @default all
             */
            portal: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SuccessResponse
         * @description Generic ``{"success": true}`` acknowledgement.
         */
        SuccessResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_or_update_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_applications_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApplicationDeleteRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_application_api_applications_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_application_api_applications_notes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applied_urls_api_applied_urls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    approved_index_api_approved_index_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedIndexEntry"][];
                };
            };
        };
    };
    get_tracker_api_crm_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_dismissed_api_dismissed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dismiss_job_api_dismissed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    generate_application_api_generate_application_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generation_status_api_generate_application_status_get: {
        parameters: {
            query?: {
                task_key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_email_api_generate_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_descriptions_api_job_descriptions_get: {
        parameters: {
            query?: {
                urls?: string;
                company?: string;
                position?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                file?: string | null;
                dataset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_and_sync_api_pull_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_scraper_api_run_scraper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScraperRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scraper_logs_api_scraper_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scraper_status_api_scraper_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stop_scraper_api_stop_scraper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    pull_and_sync_api_sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_tracker_api_tracker_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_tracker_api_tracker_refresh_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    run_scraper_api_trigger_github_scraper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScraperRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
